# Generated by Django 4.1.12 on 2023-10-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Categoria')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion de Categoria')),
            ],
        ),
    ]
