# Generated by Django 4.1.12 on 2023-11-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='_id',
            field=models.CharField(default='6557bcff50963ffd659bb123', editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
