# Generated by Django 4.1.12 on 2023-11-02 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('idViaje', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Viaje')),
                ('horaSalida', models.TimeField(verbose_name='Hora de salida')),
                ('capacidadPasajeros', models.IntegerField(verbose_name='Capacidad de Pasajeros')),
                ('estadoViaje', models.CharField(max_length=20, verbose_name='Estado del viaje')),
                ('patenteVehiculo', models.ForeignKey(blank=True, max_length=10, on_delete=django.db.models.deletion.CASCADE, to='core.vehiculo', verbose_name='Patente de vehículo de Usuario chofer')),
                ('rutConductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario', verbose_name='Rut del Conductor')),
            ],
        ),
    ]
