# Generated by Django 4.1.12 on 2023-11-17 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='correoPasajero',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Correo de Usuario Pasajero'),
            preserve_default=False,
        ),
    ]
