# Generated by Django 4.1.12 on 2023-11-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_viaje__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='_id',
            field=models.CharField(default='6558d82bcde168a77b06fc08', editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
