# Generated by Django 4.1.12 on 2023-11-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_viaje_correopasajero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='correoPasajero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Correo de Usuario Pasajero'),
        ),
    ]
