# Generated by Django 4.1.12 on 2023-11-08 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_viaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='sedeDuoc',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Sede Duoc'),
            preserve_default=False,
        ),
    ]
