# Generated by Django 4.1.12 on 2023-12-06 19:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_viaje_capacidadpasajeros_alter_viaje__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='_id',
            field=models.CharField(default=core.models.get_objectid, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
